services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: jpfrontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: jpbackend
    ports:
      - "3700:80"
    networks:
      - app-network

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
